### ISSUE TITLE
Can we get a nicer screenshot, to be reference in press? 

### ISSUE THREAD

**Issue by it33** [mattermost/mattermost-ai-framework#11]
This was okay for a placeholder, we should try for something slightly nicer: 
![haiku](https://user-images.githubusercontent.com/46905241/238375143-bbdce0f0-08ba-4934-bf94-6ff55d3cc6e7.png)

**Comment by azigler** [comment]
I agree @it33. @asaadmahmood What do you think about making a stylized screenshot to be the header image for this repository? It could tie in with your `ai.mattermost.com` theme and that would also improve cohesion between them.

**Comment by asaadmahmood** [comment]
@it33 @azigler What's the size that we need for the press release?

**Comment by azigler** [comment]
@asaadmahmood @it33 This repository will be linked so I think the image just needs to service this repo. I would follow the [GitHub social preview guidelines](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/customizing-your-repositorys-social-media-preview) to make an image adhering to that ratio (but doesn't need to be very big). Then we can use it both at the top of the README and in the repository's settings.

**Comment by asaadmahmood** [comment]
Done.

**Comment by it33** [comment]
Thanks @asaadmahmood @azigler!
